import { Playfair } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";

const playfair = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth" suppressHydrationWarning>
      <body className={playfair.className}>{children}</body>
    </html>
  );
}
